"""Thread-safe Kenwood CAT serial transport."""

from __future__ import annotations

from dataclasses import dataclass
import threading
import time
from typing import Callable, Optional

import serial

from errors import CATError, CATTimeoutError


TrafficCallback = Callable[[str, str], None]
InformationCallback = Callable[[str], None]


@dataclass(frozen=True, slots=True)
class SerialSettings:
    port: str
    baud_rate: int
    timeout_seconds: float = 0.7
    stop_bits: int = 1
    protocol: str = "semicolon_ascii"
    civ_address: int = 0x94
    controller_address: int = 0xE0


class CATEngine:
    """Own one serial connection and serialize all CAT traffic."""

    def __init__(
        self,
        traffic_callback: Optional[TrafficCallback] = None,
        information_callback: Optional[InformationCallback] = None,
    ) -> None:
        self._serial: Optional[serial.Serial] = None
        self._lock = threading.RLock()
        self._traffic_callback = traffic_callback
        self._information_callback = information_callback
        self.settings: Optional[SerialSettings] = None
        self._pending_input = bytearray()

    @property
    def is_open(self) -> bool:
        return self._serial is not None and self._serial.is_open

    def open(self, settings: SerialSettings) -> None:
        self.close()
        try:
            serial_port = serial.Serial(
                port=settings.port,
                baudrate=settings.baud_rate,
                bytesize=serial.EIGHTBITS,
                parity=serial.PARITY_NONE,
                stopbits=serial.STOPBITS_TWO if settings.stop_bits == 2 else serial.STOPBITS_ONE,
                timeout=0.04,
                write_timeout=0.5,
                rtscts=False,
                dsrdtr=False,
                xonxoff=False,
            )
        except (OSError, serial.SerialException) as exc:
            raise CATError(str(exc)) from exc

        with self._lock:
            self._serial = serial_port
            self.settings = settings
            try:
                serial_port.reset_input_buffer()
                serial_port.reset_output_buffer()
                self._pending_input.clear()
            except serial.SerialException as exc:
                self._serial = None
                self.settings = None
                serial_port.close()
                raise CATError(str(exc)) from exc

    def close(self) -> None:
        with self._lock:
            serial_port = self._serial
            self._serial = None
            self.settings = None
            self._pending_input.clear()
            if serial_port is not None:
                try:
                    if serial_port.is_open:
                        serial_port.close()
                except serial.SerialException:
                    pass

    def query(self, command: str) -> str:
        if self.settings and self.settings.protocol == "icom_civ":
            return self._civ_transaction(command, False)
        command = self._normalise(command)
        expected_prefix = command[:-1]
        with self._lock:
            serial_port, settings = self._require_open()
            try:
                # Auto Information and replies generated by earlier set
                # commands may already be waiting.  Dispatch them before a
                # new query so a stale same-prefix message cannot masquerade
                # as the fresh answer and create seconds of apparent lag.
                self._drain_pending(serial_port)
                self._emit("TX", command)
                serial_port.write(command.encode("ascii", errors="strict"))
                serial_port.flush()
            except (OSError, serial.SerialException, serial.SerialTimeoutException) as exc:
                raise CATError(str(exc)) from exc

            deadline = time.monotonic() + settings.timeout_seconds
            received = bytearray()
            while time.monotonic() < deadline:
                try:
                    chunk = serial_port.read(1)
                except (OSError, serial.SerialException) as exc:
                    raise CATError(str(exc)) from exc
                if not chunk:
                    continue
                received.extend(chunk)
                if chunk == b";":
                    reply = received.decode("ascii", errors="replace").strip()
                    self._emit("RX", reply)
                    received.clear()
                    if reply.startswith(expected_prefix) or reply in ("?;", "E;", "O;"):
                        return reply
                    if self._information_callback is not None:
                        self._information_callback(reply)

            partial = received.decode("ascii", errors="replace")
            raise CATTimeoutError(f"No complete CAT reply. Partial response: {partial!r}")

    def set(self, command: str) -> None:
        if self.settings and self.settings.protocol == "icom_civ":
            self._civ_transaction(command, True)
            return
        command = self._normalise(command)
        with self._lock:
            serial_port, _settings = self._require_open()
            try:
                self._emit("TX", command)
                serial_port.write(command.encode("ascii", errors="strict"))
                serial_port.flush()
            except (OSError, serial.SerialException, serial.SerialTimeoutException) as exc:
                raise CATError(str(exc)) from exc

    def _require_open(self):
        if not self.is_open or self._serial is None or self.settings is None:
            raise CATError("Serial port is not open.")
        return self._serial, self.settings

    def _civ_transaction(self, command: str, write: bool) -> str:
        """Exchange hexadecimal payloads; framing and addressing live here."""
        payload = bytes.fromhex(command)
        if not payload:
            raise CATError("Empty CI-V command.")
        with self._lock:
            port, settings = self._require_open()
            frame = bytes((0xFE, 0xFE, settings.civ_address, settings.controller_address)) + payload + b"\xfd"
            # Discard only pre-existing input, before this transaction starts.
            waiting = int(getattr(port, "in_waiting", 0))
            if waiting:
                stale = port.read(waiting)
                self._emit("RX", stale.hex(" ").upper())
            try:
                self._emit("TX", frame.hex(" ").upper())
                port.write(frame)
                port.flush()
                deadline = time.monotonic() + settings.timeout_seconds
                buffer = bytearray()
                while time.monotonic() < deadline:
                    chunk = port.read(1)
                    if not chunk:
                        continue
                    buffer.extend(chunk)
                    if len(buffer) > 4096:
                        buffer.clear()
                    if chunk != b"\xfd":
                        continue
                    raw = bytes(buffer)
                    buffer.clear()
                    start = raw.find(b"\xfe\xfe")
                    if start < 0:
                        continue
                    raw = raw[start:]
                    while raw.startswith(b"\xfe\xfe\xfe"):
                        raw = raw[1:]
                    self._emit("RX", raw.hex(" ").upper())
                    if len(raw) < 6 or raw[2:4] != bytes((settings.controller_address, settings.civ_address)):
                        continue  # echo, broadcast, or another station
                    answer = raw[4:-1]
                    if answer == b"\xfa":
                        raise CATError("Radio rejected CI-V command (NAK).")
                    if write:
                        if answer == b"\xfb":
                            return answer.hex().upper()
                    elif answer.startswith(payload):
                        return answer.hex().upper()
                raise CATTimeoutError("No matching CI-V reply from the selected radio address.")
            except (OSError, serial.SerialException) as exc:
                raise CATError(str(exc)) from exc

    def _drain_pending(self, serial_port) -> None:
        try:
            while True:
                waiting = int(getattr(serial_port, "in_waiting", 0))
                if waiting <= 0:
                    break
                self._pending_input.extend(serial_port.read(waiting))
        except (OSError, serial.SerialException) as exc:
            raise CATError(str(exc)) from exc

        while b";" in self._pending_input:
            end = self._pending_input.index(ord(";")) + 1
            raw = bytes(self._pending_input[:end])
            del self._pending_input[:end]
            message = raw.decode("ascii", errors="replace").strip()
            if not message:
                continue
            self._emit("RX", message)
            if self._information_callback is not None:
                self._information_callback(message)

    @staticmethod
    def _normalise(command: str) -> str:
        command = command.strip()
        return command if command.endswith(";") else command + ";"

    def _emit(self, direction: str, text: str) -> None:
        if self._traffic_callback is not None:
            self._traffic_callback(direction, text)
